### ISSUE TITLE
Update to 3.0.1

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/constructor-feedstock#24]
Would be good to update to `3.0.1`. Requires a [few changes to the dependencies]( https://github.com/conda/constructor/compare/3.0.0...3.0.1#diff-bd134fa847b11c75aba174f834eb80df ).

Also has a new dependency `conda-standalone`. Have raised issue ( https://github.com/conda-forge/staged-recipes/issues/10160 ) about packaging it.

**Comment by hadim** [comment]
See https://github.com/conda-forge/constructor-feedstock/pull/26
