### ISSUE TITLE
Support for aarch64

### ISSUE THREAD

**Issue by hadim** [conda-forge/constructor-feedstock#25]
`aarch64` build is not available because `conda.exe` does not exist for it. See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=61270

The solution would be to have a `conda-standalone` build for `arch64`. See https://github.com/conda-forge/constructor-feedstock/issues/24

Once fixed, this issue should also fix https://github.com/conda-forge/miniforge/pull/2

**Comment by hmaarrfk** [comment]
I don't get why standalone is necessary.

Upstream doesn't seem to use it in their package

https://github.com/conda/constructor/blob/master/conda.recipe/meta.yaml

**Comment by hadim** [comment]
It's a required dep since 3.0.1: https://github.com/conda/constructor/blob/master/conda.recipe/meta.yaml#L25

**Comment by hadim** [comment]
conda-standalone is the new way to provide `conda.exe`. It put the executable into `PREFIX/conda-standalone`. So you can get away without it but then you have to provide yourself the `conda-standalone` executable.

At least this is my understanding of the situation.

**Comment by hadim** [comment]
The associated code is here: https://github.com/conda/constructor/blob/71929a3b6d0e73ad5578ad4ed8abd144f95b471d/constructor/main.py#L231

**Comment by hadim** [comment]
See https://github.com/conda-forge/constructor-feedstock/pull/26

**Comment by hmaarrfk** [comment]
I guess it is all open source software. What do we need to do to build it?

**Comment by hadim** [comment]
Yes it is. See https://github.com/conda-forge/miniforge/pull/2#issuecomment-554407239

**Comment by hmaarrfk** [comment]
yeah, jsut saw it, thanks!
