### ISSUE TITLE
Remove old constructor conda packages in conda-forge channel?

### ISSUE THREAD

**Issue by megies** [conda-forge/constructor-feedstock#7]
There's some old 1.3.x constructor conda packages in conda-forge channel, but it seems distribution was completely handed over to Anaconda defaults channel.. for people that have conda-forge as top priority channel this means that by default old constructor packages get installed if you don't pay close attention.. (I didn't pay too much attention until bumping into already fixed #57)

I would propose to remove all constructor conda packages from conda-forge channel, since all versions are readily available through defaults.

See conda/constructor#82.

**Comment by jakirkham** [comment]
Feel free to send a PR to update it.

**Comment by megies** [comment]
Sorry but I'm not aware of the package removal mechanics. I only know that new packages are built and uploaded on every push to the feedstock.

**Comment by jakirkham** [comment]
Sorry I was suggesting that you could send a PR to update the package.

**Comment by megies** [comment]
Is it still needed in `conda-forge`? It seems to be reasonably up to date in `defaults` channel..   ah, anyway, i'll send a PR..

**Comment by hammerdirt** [comment]
I followed an issue to here, from here [https://github.com/conda/constructor/issues/57](https://github.com/conda/constructor/issues/57 )
Just received the same return: **Bus error (core dumped)** running _conda update conda_ 
conda version: 4.3.23
ubuntu: 16.04.3, xenial

What is the fix precisely?

**Comment by jakirkham** [comment]
Not sure how that is related, @hammerdirt. :man_shrugging: Maybe raise a fresh issue upstream and see what they suggest and/or update after new packages are released here to see if the issue continues.

**Comment by jakirkham** [comment]
Since the package is updated to the latest known release. Am closing this out as resolved.

**Comment by hammerdirt** [comment]
It was an issue with the default library and conda forge, changed the .condarc file to
defaults and added conda forge at the command line.  have not had a problem on either ubunt or lubuntu
